=== amjyebenes/Ejercicios-LMSGI/DTDEjercicios/EntregaDragonBall/Dragonball.dtd
<!ENTITY % caracteristicas "identificador ID #REQUIRED nombre CDATA #IMPLIED evolucion ID #IMPLIED">
<!ELEMENT universo (goku*, trunk+, celula?, krilin)*>
<!ELEMENT goku EMPTY>
<!ATTLIST goku %caracteristicas;
                amistad IDREF #REQUIRED>

<!ELEMENT trunk EMPTY>
<!ATTLIST trunk %caracteristicas;
                arma_utilizada CDATA #IMPLIED>

<!ELEMENT celula EMPTY>
<!ATTLIST celula %caracteristicas;
                 nivel_potencia CDATA #IMPLIED>

<!ELEMENT krilin (#PCDATA | mision)*>
<!ATTLIST krilin   %caracteristicas;
                    cabello NMTOKENS #FIXED (calvo | pelo_corto | pelo_largo)>

<!ELEMENT mision (objetivo, (aliados | enemigos)*)>
<!ELEMENT objetivo (#PCDATA)>
<!ELEMENT aliados (#PCDATA)>
<!ELEMENT enemigos (#PCDATA)>

<!ELEMENT serie EMPTY>
<!ATTLIST serie personajes IDREFS #REQUIRED
                evoluciones  IDREFS #REQUIRED>

=== amjyebenes/Ejercicios-LMSGI/DTDEjercicios/EntregaDragonBall/Dragonball.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE universo SYSTEM "Dragonball.dtd">
<universo>
    <goku identificador="SG" nombre="Son Goku" evolucion="SS6" amistad="T"/>
    <trunk identificador="T" nombre="Trunks" evolucion="SS" arma_utilizada="espada"/>
    <celula identificador="CEL" nombre="Celula" evolucion="N2" nivel_potencia="megasuper"/>
    <krilin identificador="K" nombre="Krilin Maquina" evolucion="SS4" cabello="calvo">
        <mision>
            <objetivo>
                Cazar a Celula
            </objetivo>
            <aliados>
                Goku y compa√±ia
            </aliados>
        </mision>
    </krilin>
    <serie personajes="TK K2 CEL" evoluciones="Super SS5 N2"/>
    <trunk identificador="TK" nombre="Trunks 2" evolucion="SS5" arma_utilizada="katana"/>
    <celula identificador="CEL2" nombre="Super Celula" evolucion="Super" nivel_potencia="maxima"/>
    <krilin identificador="K2" nombre="Krilin" evolucion="SS2" cabello="pelo_largo" actitud="cabreado">
        Krilin ataca de nuevo
    </krilin>
    <serie personajes="SG T K" evoluciones="SS2 SS4"/>
</universo>
