<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE animales[
    <!ENTITY % attcarnivoros "<!ATTLIST carnivoros nombre ID #REQUIRED especie NMTOKEN #IMPLIED>">
    <!ENTITY % attherviboros "<!ATTLIST herviboros nombre ID #REQUIRED especie NMTOKEN #IMPLIED>">
    <!ELEMENT animales (carnivoro*, herbivoro+, omnivoro?, insecto)*>
    <!ELEMENT animal EMPTY>
    <!ELEMENT herbivoro EMPTY>  
    <!ELEMENT carnivoro EMPTY>      
    <!ELEMENT omnivoro EMPTY>
    <!ELEMENT insecto (#PCDATA | nombrecientifico)*>
    <!ELEMENT nombrecientifico (#PCDATA)>
]>
<animales>
    <carnivoro/>
    <insecto>
    </insecto>
    <carnivoro/>
    <insecto>
    </insecto>
    <carnivoro/>
    <insecto>
    </insecto>
    <carnivoro/>
    <insecto>
    </insecto>
</animales>
